### ISSUE TITLE
feature request: support "docker load" like functionality for input caching

### ISSUE THREAD

**Issue by eedwards-sk** [concourse/builder-task#16]
while there is support for build caches already, this doesn't solve a use case where you want to start with layers from a previous image build without having a local build cache

ideally, I would be able to provide an input `image.tar` file as an input cache

this image would then be loaded before the build starts, so any cached layers (with no changes) are not rebuilt

similar to a "docker load", except since this task library doesn't really deal with repositories, that could be handled by an upstream resource that saves the `image.tar` file and passes it to this task

not sure if this is possible based on a cursory glance at `img` itself, but I wanted to toss out this use case either way

**Comment by jbhannah** [comment]
I ran into this too, so I made a builder that [uses BuildKit directly](https://github.com/issho-ni/concourse-buildkit) and takes advantage of the ability to save the build cache either locally or to a registry. The script within the image itself is more complex but the usage of it is largely the same (and it's building itself!).

**Comment by vito** [comment]
@jbhannah Interesting! Maybe we should just switch to using buildkit directly?

@cirocosta also has a buildkit task here: https://github.com/cirocosta/buildkit-task

**Comment by vito** [comment]
@jbhannah I went ahead and wrote a new task which uses `buildkit` directly under the hood: https://github.com/vito/oci-build-task - I had been wanting to rewrite it with tests and in Go so that was a good centerpiece for the refactor. :slightly_smiling_face: 

@eedwards-sk I'm going to archive this repo, so I'll close this issue. The equivalent feature request on the new task is here: https://github.com/vito/oci-build-task/issues/1
