### ISSUE TITLE
How to run the build image without uploading to a registry?

### ISSUE THREAD

**Issue by databus23** [concourse/builder-task#24]
Wouldn't it be nice if images build with this task could be run without uploading?
It seems to me this is currently not possible to do something like this:
```
    - task: build
      privileged: true
      file: input.git/ci/build.yaml
    - task: test
      image: image/
      file: input.git/ci/run.yaml
```
According to https://concourse-ci.org/tasks.html#task-image-resource
> You can use any resource that returns a filesystem in the correct format (a /rootfs directory and a metadata.json file in the top level)

Currently this task outputs a tarball of the image which does not work with the `image:` key I suppose.

Is this correct or I'm I missing something? has this been done by somebody already?
If its missing I guess the tricky part would be get the content of `metadata.json` correct.

**Comment by vito** [comment]
Yeah, this is a gap right now - I think it's listed as a goal in the README but I never got around to this aspect.

IMO in the long run Concourse should switch to OCI tarballs instead of having our own `rootfs/ + metadata.json` format. Until then we'll need to extend this task to support producing the rootfs tree and metadata. The metadata file actually isn't too difficult - it just contains the user and env configured by the image:

https://github.com/concourse/docker-image-resource/blob/master/cmd/print-metadata/main.go#L14-L17

This information could probably be extracted from the OCI tarball, similar to 

For creating the `rootfs/` path, maybe we can make use of `img unpack`? Tried it out locally and it feels pretty simple.

https://github.com/genuinetools/img#unpack-an-image-to-a-rootfs

**Comment by databus23** [comment]
@vito I took a little stab at this but ran into problems trying to unpack the roofs using `img unpack` in the task container:

```
/tmp/build/e55deab7 # img unpack -o image/rootfs image/image.tar
creating worker opt failed: failed to find runc binary
```

Seems like there is some foo going on with the `runc` binary that is embedded in `img`:
https://github.com/genuinetools/img/issues/233

Update 1:
I found a `runc` binary that is unpacked in `/tmp`. But trying to unpack the image hangs at the first layer:
```
PATH=/tmp/img-runc553031232:$PATH img unpack -s /scratch/state -o image/roots -d myimage:mytag
DEBU[0000] using backend: overlayfs
DEBU[0000] Unpacking layer sha256:e7c96db7181be991f19a9fb6975cdbbd73c65f4a2681348e63a141a2192a5f10
(hangs)
```
I also tried switching the backend to `native`, that bombs out with yet another error:
```
PATH=/tmp/img-runc553031232:$PATH img unpack -s /scratch/state -o image/roots -b native -d myimage:mytag
getting image myimage:mytag from image store failed: image "myimage:mytag": not found
```
So it seems using `img unpack` is not as straight forwards as we hoped.

Update 2:
Unpacking to `/scratch` seems to work. 💃 
```
 PATH=/tmp/img-runc553031232:$PATH img unpack -s /scratch/state -o /scratch/rootfs -d myimage:mytag
DEBU[0000] using backend: overlayfs
DEBU[0000] Unpacking layer sha256:e7c96db7181be991f19a9fb6975cdbbd73c65f4a2681348e63a141a2192a5f10
DEBU[0000] Unpacking layer sha256:25dd63d8a6b248b1b1fc9379622c21a049dd142022e218029f20e16d80c8506b
DEBU[0000] Unpacking layer sha256:95a84f2afbe6960d828956ac1f315f10fb71032eed2a4efb7bd8424f9c651341
Successfully unpacked rootfs for myimage:mytag to: /scratch/rootfs
```


Generating the metadata.json is pretty simple with these two lines indeed:
```
  imageConfig=$(tar -Oxf image.tar manifest.json | jq -r '.[0].Config')
  tar -Oxf image.tar $imageConfig | jq '{"user":.config.User,"env":.config.Env}' > image/metadata.json
```
