### ISSUE TITLE
Provide more compelling (integration) examples

### ISSUE THREAD

**Issue by brunocous** [concourse/builder-task#38]
The example.yml is confusing and unreadable. Is it a task? How should I integrate it? What is it exactly building? Where does it get the resources from? 

It would also be helpful to have an example how to integrate with registry-image-resource (something similar as in https://github.com/concourse/registry-image-resource/issues/40), as most of us will be integrating with that.

If I wasn't "obliged" to use this for my project, I would have thrown it away immediately because of the lack of clear examples. Yet it costed me way too much time to get this thing to work.

**Comment by vito** [comment]
FWIW, the README already mentions the `example.yml` task and shows how to run it: https://github.com/concourse/builder-task#example

There could definitely be better examples. There's not much yet because we don't expect everyone to be using it as their first option yet. I'm not sure why you were obliged to use it, but until it's fully ready I would recommend just opening issues like this or - better yet - submitting PRs to make things easier for the next person. :slightly_smiling_face:

**Comment by vito** [comment]
The [`oci-build` task](https://github.com/vito/oci-build-task) has a much better README and has an example showing how to use it with the `registry-image` resource. Gonna close this out as this project will be deprecated in favor of the aforementioned task. Thanks!
